### ISSUE TITLE
Sending SIGHUP to jobmanagers will cause a disconnect that it doesn't recover from

### ISSUE THREAD

**Issue by com4** [eventmq/eventmq#2]
Essentially, SIGHUP should behave as expected:

The Jobmanager MUST allow all jobs executing time to finish
Jobmanager MUST reload all conf settings from file, and override the same settings it did intially from the command line (with one caveat possibly being CONCURRENT_JOBS)
Jobmanager SHOULD keep child processes alive if possible

**Comment by sideshowdave7** [comment]
I believe I reported this so I'll take a look if its still valid, and possible solutions.
